// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ompkrlqbkrotzkxjqvdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcGtybHFia3JvdHpreGpxdmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTA1NDUsImV4cCI6MjA3MDQ4NjU0NX0.pHH9tm0cGbTvl9IDMzgdM8N_9YiodCwXtsMUh2NY_L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});